# Generated by Django 5.1.4 on 2025-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prices Name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_soch_olish', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price Soch Olish')),
                ('price_bosh_yuvish', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price Bosh yuvish')),
                ('price_soqol_olish', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price SOQOL olish')),
                ('price_for_kids', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price for kids')),
            ],
        ),
    ]
