# Generated by Django 5.1.4 on 2025-01-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azzem', '0002_barbers_barberscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azzem.barberscategory'),
        ),
    ]
